### ISSUE TITLE
Uncaught TypeError: Cannot read property '92' of undefined

### ISSUE THREAD

**Issue by lukasoppermann** [bpearson/atom-phpcs#10]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: [atom-phpcs](https://github.com/bpearson/atom-phpcs) package, v1.0.0

### Stack Trace

Uncaught TypeError: Cannot read property '92' of undefined

```
At /Users/lukasoppermann/.atom/packages/atom-phpcs/lib/atom-phpcs.coffee:77

TypeError: Cannot read property '92' of undefined
    at cursorCb (/Users/lukasoppermann/.atom/packages/atom-phpcs/lib/atom-phpcs.coffee:77:17)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at TextEditor.module.exports.TextEditor.cursorMoved (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1579:27)
    at Selection.module.exports.Selection.markerDidChange (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:926:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:41:24
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Marker.module.exports.Marker.notifyObservers (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:262:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:63:26
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:401:20)
```

### Commands

```
     -0:00.5.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:00.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:00.3.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:00.3.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "csslint",
      "git-log",
      "htmlhint",
      "fancy-new-file",
      "atom-css-comb",
      "csscomb",
      "atom-jshint",
      "block-travel",
      "block-cursor",
      "rgb",
      "task-list",
      "task-list",
      "task-list",
      "task-list",
      "atom-color-highlight"
    ],
    "themes": [
      "one-dark-ui",
      "atom-material-syntax"
    ],
    "projectHome": "/Users/lukasoppermann/Code",
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-material-syntax, v0.2.4
atom-phpcs, v1.0.0
autocomplete-paths, v1.0.2
autocomplete-phpunit, v1.0.2
color-picker, v2.0.13
css-snippets, v0.9.0
docblockr, v0.7.3
file-icons, v1.6.11
git-tab-status, v1.9.2
highlight-line, v0.11.0
jsonlint, v1.1.2
language-laravel-blade, v0.2.0
laravel, v0.7.0
php-cs-fixer, v2.5.1
recent-projects, v0.9.5

# Dev
No dev packages
```

**Comment by bpearson** [comment]
Fixed in v1.0.1
