### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by tricaalexandru** [bpearson/atom-phpcs#18]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [atom-phpcs](https://github.com/bpearson/atom-phpcs) package, v1.3.0

### Stack Trace

Uncaught Error: spawn EACCES

```
At /Users/Zender/Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260

Error: spawn EACCES
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:351:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/Users/Zender/Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
    at new BufferedProcess (/Users/Zender/Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
    at Object.module.exports.AtomPHPCS.sniffFile (/Users/Zender/.atom/packages/atom-phpcs/lib/atom-phpcs.coffee:206:17)
    at Object.module.exports.AtomPHPCS.generateErrors (/Users/Zender/.atom/packages/atom-phpcs/lib/atom-phpcs.coffee:262:19)
    at Object.module.exports.AtomPHPCS.codesniff (/Users/Zender/.atom/packages/atom-phpcs/lib/atom-phpcs.coffee:105:22)
    at module.exports.AtomPHPCS.activateEditor (/Users/Zender/.atom/packages/atom-phpcs/lib/atom-phpcs.coffee:90:23)
    at Emitter.module.exports.Emitter.emit (/Users/Zender/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at /Users/Zender/Downloads/Atom.app/Contents/Resources/app.asar/src/pane-container.js:333:27
    at Emitter.module.exports.Emitter.emit (/Users/Zender/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Pane.module.exports.Pane.setActiveItem (/Users/Zender/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:248:22)
    at Pane.module.exports.Pane.activateItem (/Users/Zender/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:312:21)
    at /Users/Zender/Downloads/Atom.app/Contents/Resources/app.asar/src/workspace.js:492:18
    at process._tickCallback (node.js:368:9)
```

### Commands

```
     -0:59.2.0 application:add-project-folder (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "ignoredNames": [
      ".*"
    ],
    "audioBeep": false
  },
  "atom-phpcs": {
    "standard": "Zend",
    "path": "/Users/Zender/bin/phpcs"
  }
}
```

### Installed Packages

```coffee
# User
atom-macros, v0.5.2
atom-phpcs, v1.3.0
docblockr, v0.7.3
emmet, v2.3.15
language-diff, v0.4.0
linter, v1.11.3
linter-jshint, v1.2.1
linter-php, v1.1.6
meteor-api, v2.20.0
php-getters-setters, v0.5.5
project-manager, v2.6.5
react, v0.12.10

# Dev
No dev packages
```

**Comment by bpearson** [comment]
Is the correct path to phpcs script at "/Users/Zender/bin/phpcs" ? I can replicate this when the path is incorrect. It needs to point at the actual script/phar file not the directory its installed too.

**Comment by tricaalexandru** [comment]
Thank you. Solved it. Was pointing it just to the directory. Cheers!
