### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setEncoding' of undefined

### ISSUE THREAD

**Issue by cjwilburn** [bpearson/atom-phpcs#19]
## Steps to reproduce ##
1. Write any php or Laravel Blade template code.
2. Attempt to save your file (it will hang on command-S for 5-7 seconds).
3. You will receive the below error message.

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [atom-phpcs](https://github.com/bpearson/atom-phpcs) package, v1.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'setEncoding' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:825

TypeError: Cannot read property 'setEncoding' of undefined
    at BufferedProcess.module.exports.BufferedProcess.bufferStream (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:74:13)
    at BufferedProcess.module.exports.BufferedProcess.handleEvents (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:218:14)
    at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:55:12)
    at Object.module.exports.AtomPHPCS.sniffFile (/Users/courtneywilburn/.atom/packages/atom-phpcs/lib/atom-phpcs.coffee:206:17)
    at Object.module.exports.AtomPHPCS.generateErrors (/Users/courtneywilburn/.atom/packages/atom-phpcs/lib/atom-phpcs.coffee:262:19)
    at Object.module.exports.AtomPHPCS.codesniff (/Users/courtneywilburn/.atom/packages/atom-phpcs/lib/atom-phpcs.coffee:105:22)
    at eventCb (/Users/courtneywilburn/.atom/packages/atom-phpcs/lib/atom-phpcs.coffee:81:27)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1067:27)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1037:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:630:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:545:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:528:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:649:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -9:54 core:backspace (atom-text-editor.editor.is-focused)
     -9:46.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -9:45.9.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:35.7.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-jshint"
    ],
    "themes": [
      "atom-solarized-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "atom-phpcs": {
    "cbfpath": "/Users/courtneywilburn/.composer/vendor/bin/phpcbf",
    "path": "/Users/courtneywilburn/.composer/vendor/bin/phpcs"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
atom-beautify, v0.28.22
atom-jade, v0.3.0
atom-phpcs, v1.3.0
atom-solarized-dark-ui, v0.25.0
atom-trello, v0.5.1
autocomplete-phpunit, v1.0.2
change-case, v0.6.0
color-picker, v2.1.1
drupal, v1.8.0
file-icons, v1.6.14
git-log, v0.4.1
language-api-blueprint, v1.0.2
language-blade, v0.20.0
language-cfml, v0.11.0
language-drupal, v0.4.2
language-ejs, v0.2.0
language-elm, v1.3.2
language-mediawiki, v2.0.0
language-scala, v1.1.6
language-yaml, v0.25.1
laravel, v0.7.0
linter, v1.11.3
linter-csslint, v1.3.1
linter-js-yaml, v1.2.5
linter-jsonlint, v1.1.5
linter-pep8, v1.2.1
linter-php, v1.1.8
linter-phpcs, v1.3.0
linter-phpmd, v1.4.1
linter-pylint, v1.2.0
linter-rubocop, v0.4.7
linter-ruby, v1.2.1
linter-scss-lint, v2.5.1
linter-shellcheck, v1.1.0
linter-xo, v0.12.0
phpunit, v1.2.0
phpunit-snippets, v0.1.0
pigments, v0.24.1
tabs-to-spaces, v1.0.2
travis-ci-status, v1.0.0
vagrant, v0.1.0

# Dev
No dev packages
```

**Comment by bpearson** [comment]
I can't replicate this issue, can you please verify that phpcs works and the path is correct? And maybe try with other community packages disabled? It looks like the issue is with BufferedProcess not returning the process so atom-phpcs can get the output
