### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by kmcconnell** [bpearson/atom-phpcs#20]
[Enter steps to reproduce below:]
1. This seems to happen every time a file is deleted from the project.

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [atom-phpcs](https://github.com/bpearson/atom-phpcs) package, v1.3.0
### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/decoration-manager.js:192

Error: Cannot decorate a destroyed marker
    at DecorationManager.module.exports.DecorationManager.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/decoration-manager.js:192:15)
    at TextEditor.module.exports.TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1540:37)
    at Object.module.exports.AtomPHPCS.addError (/Users/kanemcconnell/.atom/packages/atom-phpcs/lib/atom-phpcs.coffee:266:29)
    at module.exports.AtomPHPCS.renderErrors (/Users/kanemcconnell/.atom/packages/atom-phpcs/lib/atom-phpcs.coffee:282:31)
    at /Users/kanemcconnell/.atom/packages/atom-phpcs/lib/atom-phpcs.coffee:198:30
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:237:18)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```
### Commands

```
     -2:34.6.0 application:add-project-folder (atom-text-editor.editor.is-focused)
  3x -2:03.1.0 tree-view:remove (span.name.icon.icon-file-directory)
     -0:14.3.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "markdown-preview"
    ],
    "excludeVcsIgnoredPaths": false,
    "packagesWithKeymapsDisabled": [
      "blame",
      "git-blame"
    ]
  },
  "atom-phpcs": {
    "standard": "PSR2"
  }
}
```
### Installed Packages

``` coffee
# User
atom-pair, v2.0.10 (active)
atom-phpcs, v1.3.0 (active)
autocomplete-php, v0.3.7 (active)
git-blame, v0.4.11 (inactive)
language-apache, v1.5.0 (active)
linter, v1.11.16 (active)
linter-markdown, v3.0.1 (active)
linter-php, v1.2.0 (active)
linter-phpcs, v1.4.1 (active)
linter-phpmd, v1.5.1 (active)
markdown-preview-plus, v2.4.0 (active)
php-analyser, v0.2.0 (active)
php-cs-fixer, v2.5.9 (active)
php-debug, v0.2.3 (active)
php-introspector, v1.0.0 (active)
todo-show, v1.7.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by bpearson** [comment]
Weird, I can't replicate this issue. In Atom, it just removes the file and closes any open tab of the file. Outside of Atom, it doesn't do anything, but if I run atom-phpcs on the open tab of the deleted file, it spits out a message in the console "Atom-phpcs is not setup correctly". Did I miss anything?

**Comment by kmcconnell** [comment]
Not entirely sure. When I delete, or sometimes just changing branches in the repo, I get a whole series of the these filling up the right gutter. Even after closing all, a few more pop up if the change is large enough. I'll keep an eye on it as it happens often and start collecting what's going on at the moment.

**Comment by bpearson** [comment]
Closing, unable to replicate. Please open another issue if you see it in future.

**Comment by kikoseijo** [comment]
ITs still here:

Error: Cannot decorate a destroyed marker
    at DecorationManager.module.exports.DecorationManager.decorateMarker (/Applications/Atom.app/Contents/Resources/app/src/decoration-manager.js:194:23)
    at TextEditor.module.exports.TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1737:43)
    at Object.addError (/Users/smac/.atom/packages/atom-phpcs/lib/atom-phpcs.coffee:277:25)
    at renderErrors (/Users/smac/.atom/packages/atom-phpcs/lib/atom-phpcs.coffee:295:21)
    at exit (/Users/smac/.atom/packages/atom-phpcs/lib/atom-phpcs.coffee:208:20)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:351:17
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
