### ISSUE TITLE
Uncaught TypeError: Cannot read property 'TextEditor' of undefined

### ISSUE THREAD

**Issue by fpfgithub** [bpearson/atom-phpcs#31]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 ia32
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [atom-phpcs](https://github.com/bpearson/atom-phpcs) package 1.7.0

### Stack Trace

Uncaught TypeError: Cannot read property 'TextEditor' of undefined

```
At C:\Users\Administrator\.atom\packages\atom-phpcs\lib\atom-phpcs.coffee:64

TypeError: Cannot read property 'TextEditor' of undefined
    at workspaceCb (/packages/atom-phpcs/lib/atom-phpcs.coffee:64:21)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /app.asar/src/pane-container.js:348:27
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.setActiveItem (/app.asar/src/pane.js:300:22)
    at Pane.module.exports.Pane.removeItem (/app.asar/src/pane.js:581:16)
    at Pane.module.exports.Pane.destroyItem (/app.asar/src/pane.js:658:16)
    at TabBarView.module.exports.TabBarView.closeTab (/app.asar/node_modules/tabs/lib/tab-bar-view.js:333:26)
    at HTMLDivElement.TabView.didClickCloseIcon (/app.asar/node_modules/tabs/lib/tab-bar-view.js:222:19)
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
atom-miku 2.2.5 
atom-phpcs 1.7.0 
command-toolbar 1.0.12 
ctags-status 1.3.7 
docblockr 0.9.4 
expose 0.14.0 
file-icons 2.1.2 
git-control 0.9.0 
global-background 0.4.0 
language-markdown 0.20.0 
linter 2.1.2 
linter-markdown 3.1.0 
linter-php 1.3.2 
markdown-format 2.5.1 
markdown-preview-plus 2.4.9 
markdown-scroll-sync 2.1.2 
markdown-writer 2.6.4 
minimap 4.27.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
php-class-tree 1.0.0 
php-debug 0.2.4 
php-fmt 0.1.2 
php-server 0.7.0 
script 3.14.1 
sublime-block-comment 0.5.1 
Sublime-Style-Column-Selection 1.7.4 
tool-bar 1.1.0 
```

**Comment by bpearson** [comment]
Fixed in 1.7.1
