### ISSUE TITLE
Failed to activate the atom-phpcs package

### ISSUE THREAD

**Issue by chazwize** [bpearson/atom-phpcs#32]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [atom-phpcs](https://github.com/bpearson/atom-phpcs) package 1.7.2

### Stack Trace

Failed to activate the atom-phpcs package

```
At Cannot read property 'TextEditor' of undefined

TypeError: Cannot read property 'TextEditor' of undefined
    at workspaceCb (/packages/atom-phpcs/lib/atom-phpcs.coffee:64:10)
    at PaneContainer.module.exports.PaneContainer.observeActivePaneItem (/app.asar/src/pane-container.js:143:7)
    at Workspace.module.exports.Workspace.observeActivePaneItem (/app.asar/src/workspace.js:351:33)
    at Object.activate (/packages/atom-phpcs/lib/atom-phpcs.coffee:69:20)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:812:28
```

### Commands

```
```

### Non-Core Packages

```
atom-autocomplete-php 0.22.2 
atom-phpcs 1.7.2 
atom-typescript 11.0.1 
auto-detect-indentation 1.3.0 
busy-signal 1.3.0 
git-control 0.9.0 
git-plus 7.3.3 
git-time-machine 1.5.9 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
hyperclick 0.0.40 
intentions 1.1.2 
language-babel 2.57.2 
language-blade 0.29.0 
language-graphql 0.8.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.1.2 
language-swift 0.5.0 
language-thrift 1.0.2 
language-vue 0.21.2 
laravel 0.7.1 
linter 2.1.2 
linter-phpcs 1.6.0 
linter-ui-default 1.2.2 
MagicPython 1.0.9 
merge-conflicts 1.4.4 
minimap 4.27.1 
nuclide 0.215.0 
nuclide-format-js 0.0.36 
php-integrator-annotations 1.1.1 
php-integrator-autocomplete-plus 1.3.0 
php-integrator-call-tips 1.2.1 
php-integrator-navigation 1.1.2 
php-integrator-tooltips 1.1.5 
project-manager 3.3.4 
remote-sync 4.1.5 
set-syntax 0.3.2 
sort-lines 0.14.0 
sync-settings 0.8.1 
tool-bar 1.1.0 
```

**Comment by bpearson** [comment]
Should be fixed in 1.7.3
