### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by mbrevda** [bpearson/atom-phpcs#5]
Uncaught TypeError: Cannot read property 'path' of undefined

**Atom Version**: 0.155.0
**System**: Mac OS X 10.10.1
**Thrown From**: [atom-phpcs](https://github.com/bpearson/atom-phpcs) package, v0.5.0

### Steps To Reproduce

1. save a file

### Stack Trace

```
At /Users/mbrevda/.atom/packages/atom-phpcs/lib/atom-phpcs-view.coffee:25

TypeError: Cannot read property 'path' of undefined
  at AtomPHPCSView.module.exports.AtomPHPCSView.getConfig (/Users/mbrevda/.atom/packages/atom-phpcs/lib/atom-phpcs-view.coffee:25:44)
  at AtomPHPCSView.module.exports.AtomPHPCSView.generateErrors (/Users/mbrevda/.atom/packages/atom-phpcs/lib/atom-phpcs-view.coffee:76:19)
  at AtomPHPCSView.module.exports.AtomPHPCSView.updateErrors (/Users/mbrevda/.atom/packages/atom-phpcs/lib/atom-phpcs-view.coffee:71:6)
  at atom-text-editor.<anonymous> (/Users/mbrevda/.atom/packages/atom-phpcs/lib/atom-phpcs-view.coffee:14:8)
  at atom-text-editor.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-text-editor.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-text-editor.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

/cc @atom/core

**Comment by bpearson** [comment]
Ok, should be fixed in v0.6.0
